#!/bin/bash

if [ "$DISABLE_CLAMAV" = true ]; then
  exit 0
fi

grep -q -F 'db.fr.clamav.net' /etc/clamav/freshclam.conf || \
      echo 'DatabaseMirror db.fr.clamav.net' >> /etc/clamav/freshclam.conf

sed -i -e 's/^Foreground .*$/Foreground true/g' \
       -e 's/^LogSyslog .*$/LogSyslog true/g' \
       -e 's/^LogFacility .*$/LogFacility LOG_MAIL/g' \
       /etc/clamav/freshclam.conf

# Update virus databases
freshclam --quiet --config-file=/etc/clamav/freshclam.conf

logger -p mail.info "s6-supervise : spawning freshclam process"

exec freshclam -d >/dev/null
