#!/bin/bash

# Use the local DNS server
echo "nameserver 127.0.0.1" > /etc/resolv.conf

# Update resolv.conf in postfix queue
cp -f /etc/resolv.conf /var/mail/postfix/spool/etc/resolv.conf

logger -p mail.info "s6-supervise : spawning unbound process"
exec unbound &> /dev/stdout
