#!/bin/bash

if [ "$DISABLE_CLAMAV" = true ]; then
  exit 0
fi

grep -qiF 'TCPSocket' /etc/clamav/clamd.conf || \
     echo 'TCPSocket 3310' >> /etc/clamav/clamd.conf

sed -i -e 's/^Foreground .*$/Foreground true/g' \
       -e 's/^LogSyslog .*$/LogSyslog true/g' \
       -e 's/^LogFacility .*$/LogFacility LOG_MAIL/g' \
       /etc/clamav/clamd.conf

logger -p mail.info "s6-supervise : spawning clamd process"

exec clamd &>/dev/null
