#!/bin/bash

# Perform nice termination of Postfix, releasing resources and saving state
trap "{ postfix stop; exit 0; }" EXIT

for subdir in "" etc dev usr usr/lib usr/lib/sasl2 usr/lib/zoneinfo public maildrop; do
  mkdir -p  /var/mail/postfix/spool/$subdir
  chmod 755 /var/mail/postfix/spool/$subdir
done

# Add etc files to Postfix chroot jail
cp -f /etc/services /var/mail/postfix/spool/etc/services
cp -f /etc/hosts /var/mail/postfix/spool/etc/hosts
cp -f /etc/localtime /var/mail/postfix/spool/etc/localtime
cp -f /etc/resolv.conf /var/mail/postfix/spool/etc/resolv.conf

# Build header_checks and virtual index files
postmap /etc/postfix/header_checks
postmap /etc/postfix/virtual

# Fix permissions
chgrp -R postdrop /var/spool/postfix/public
chgrp -R postdrop /var/spool/postfix/maildrop
postfix set-permissions &>/dev/null

# Start Postfix
postfix -c /etc/postfix start

sleep infinity
