#!/bin/sh

# Fix: rsyslogd: cannot create '/var/spool/postfix/dev/log': No such file or directory
mkdir -p  /var/mail/postfix/spool/dev
chmod 755 /var/mail/postfix/spool/dev

exec rsyslogd -n -f /etc/rsyslog/rsyslog.conf
