#!/bin/bash

# Perform nice termination of Postfix, releasing resources and saving state
trap "{ postfix stop; exit 0; }" EXIT

for subdir in "" usr usr/lib usr/lib/sasl2 usr/lib/zoneinfo public maildrop; do
  mkdir -p  /var/mail/postfix/spool/$subdir
  chmod 755 /var/mail/postfix/spool/$subdir
done

# Add etc files to Postfix chroot jail
cp -f /etc/services /var/mail/postfix/spool/etc/services
cp -f /etc/hosts /var/mail/postfix/spool/etc/hosts
cp -f /etc/localtime /var/mail/postfix/spool/etc/localtime

# Build header_checks and virtual index files
postmap /etc/postfix/header_checks
postmap /etc/postfix/virtual

# Fix permissions
chgrp -R postdrop /var/mail/postfix/spool/public
chgrp -R postdrop /var/mail/postfix/spool/maildrop
postfix set-permissions &>/dev/null

if [ "$ENABLE_ENCRYPTION" = true ]; then

  # Add Zeyple user
  adduser --quiet \
          --system \
          --group \
          --home /var/mail/zeyple \
          --no-create-home \
          --disabled-login \
          --gecos "zeyple automatic GPG encryption tool" \
          zeyple

  # Create all files and directories needed by Zeyple
  mkdir -p /var/mail/zeyple/keys
  chmod 700 /var/mail/zeyple/keys
  chmod 744 /usr/local/bin/zeyple.py
  chown -R zeyple:zeyple /var/mail/zeyple /usr/local/bin/zeyple.py

  if [ "$TESTING" = true ]; then

  touch /var/log/zeyple.log
  chown zeyple:zeyple /var/log/zeyple.log

# Generating John Doe GPG key
s6-setuidgid zeyple gpg --homedir "/var/mail/zeyple/keys" --batch --generate-key <<EOF
  %echo Generating John Doe GPG key
  Key-Type: default
  Key-Length: 1024
  Subkey-Type: default
  Subkey-Length: 1024
  Name-Real: John Doe
  Name-Comment: test key
  Name-Email: john.doe@domain.tld
  Expire-Date: 0
  Passphrase: azerty
  %commit
  %echo done
EOF

  fi
fi

logger -p mail.info "s6-supervise : spawning postfix process"

# Start Postfix
postfix -c /etc/postfix start

# Start dovecot run script
s6-svc -u /services/dovecot

sleep infinity
